repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-yaml

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.11  # Latest ruff version
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
    -   id: ruff-format

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
    -   id: mypy
        additional_dependencies: [types-setuptools, pydantic]

-   repo: https://github.com/executablebooks/mdformat
    rev: 0.7.19
    hooks:
    -   id: mdformat
        additional_dependencies: [mdformat-gfm, mdformat-frontmatter]

default_language_version:
    python: python3
